### PR TITLE
fix(response): correct response.writable logic

### LINKED ISSUE #779: pipeling request will lost!
### Test result:
```
=== Http server ===
Request count: 1 , Error listeners: 1
Request count: 2 , Error listeners: 1
HTTP/1.1 200 OK
Date: Wed, 20 Jul 2016 02:56:47 GMT
Connection: keep-alive
Content-Length: 1

1HTTP/1.1 200 OK
Date: Wed, 20 Jul 2016 02:56:47 GMT
Connection: keep-alive
Content-Length: 1

2

=== Toa server ===
Request count: 1 , Error listeners: 1
Request count: 2 , Error listeners: 1
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 1
X-Powered-By: Toa
Date: Wed, 20 Jul 2016 02:56:47 GMT
Connection: keep-alive

1HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 1
X-Powered-By: Toa
Date: Wed, 20 Jul 2016 02:56:47 GMT
Connection: keep-alive

2

=== Koa server ===
Request count: 1 , Error listeners: 2
Request count: 2 , Error listeners: 2
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 1
Date: Wed, 20 Jul 2016 02:56:47 GMT
Connection: keep-alive

1
```

### Reason

When server emit a `request`, `responce` instance may not have `socket` for the time being, [_http_server.js](https://github.com/nodejs/node/blob/master/lib/_http_server.js#L487), `this.writable === false` in [application.js](https://github.com/koajs/koa/blob/master/lib/application.js#L199)

### PR DESCRIPTION
**Pull request by dead-horse**
closes #779

### CODE REVIEW

File: lib/response.js [hunk 1]
```diff
@@ -478,16 +478,19 @@ module.exports = {
...
    * Checks if the request is writable.
-   * Tests for the existence of the socket
-   * as node sometimes does not set it.
    *
    * @return {Boolean}
    * @api private
    */
 
   get writable() {
+    // can't write any more after response finished
```
Comment (juliangruber) [inline lib/response.js]: this looks like it could be a handy little node module

Comment (dead-horse) [inline lib/response.js]: haha, I think support by node core is more reasonable.

https://github.com/nodejs/node/blob/master/lib/_http_outgoing.js#L61 `response.writable` is never changed.

**Comment by fengmk2** [comment]
LGTM

File: lib/response.js [hunk 2]
```diff
@@ -478,16 +478,19 @@ module.exports = {
...
+    if (this.res.finished) return false;
+
     var socket = this.res.socket;
-    if (!socket) return false;
+    // There are already pending outgoing res, but still writable
+    // https://github.com/nodejs/node/blob/v4.4.7/lib/_http_server.js#L486
+    if (!socket) return true;
```
Comment (jonathanong) [inline lib/response.js]: interesting. if the socket doesn't exist, couldn't it also be that the connection was closed?

**Comment by jonathanong** [comment]
don't 100% understand it but writing to a broken connection shouldn't raise any issues, so it's ok to me

File: lib/response.js (hunk 2 above)
Comment (dead-horse) [inline lib/response.js]: socket will always assigned to res (https://github.com/nodejs/node/blob/v4.4.7/lib/_http_server.js#L517). even it is closed,(but socket.writable will set to false).

Comment (dead-horse) [inline lib/response.js]: wait. not sure if [this](https://github.com/nodejs/node/blob/v4.4.7/lib/_http_server.js#L433) will make res.socket not exists, but this too extreme anyway.

File: lib/response.js (hunk 1 above)
Comment (dougwilson) [inline lib/response.js]: In case anyone is wondering, this change seems fine to me, and of course checking the flag really doesn't quality to have it's own module. FWIW, the following I found to work on all Node.js versions as far back as 0.8: https://github.com/jshttp/on-finished/blob/v2.3.0/index.js#L70

It is literally the same code that is in here now, but as a single line :)
