### PR TITLE
Cache the request IP

### LINKED ISSUE #695: Sometimes request.ip returns undefined
After certain types of errors (e.g. `{ [Error: Parse Error] bytesParsed: 159, code: 'HPE_INVALID_METHOD' }`) the remote socket gets closed, and calling `.remoteAddress` on it will return `undefined`. 

Because koa's `request.ip` is lazy, this means it's sometimes returning  `undefined` which screws up some things (e.g. I record errors in a format that requires an ip, and would like to see the ip address of the bad requests).

I think this is quite unexpected behavior, and would be more sensible to strictly evaluate `.ip` to always be available

### PR DESCRIPTION
**Pull request by PlasmaPower**
Resolves #695

### CODE REVIEW

File: lib/application.js [hunk 1]
```diff
@@ -158,6 +158,11 @@ module.exports = class Application extends Emitter {
       keys: this.keys,
       secure: request.secure
     });
+    if (req && req.headers) {
+      request.ip = request.ips[0] || req.socket.remoteAddress || '';
+    } else {
+      request.ip = ''; // We are in a badly written test :P
```
Comment (PlasmaPower) [inline lib/application.js]: Should I also check the environment? I wasn't quite sure on this one.

File: test/helpers/context.js [hunk 2]
```diff
@@ -4,7 +4,7 @@
 const Stream = require('stream');
 const Koa = require('../..');
 
-module.exports = (req, res) => {
+module.exports = (req, res, app) => {
```
Comment (PlasmaPower) [inline test/helpers/context.js]: Needed to set `app.proxy` before the context is created.

File: lib/application.js (hunk 1 above)
Comment (RHavar) [inline lib/application.js]: I don't think using '' is particularly better than `undefined`. I'd remove the || ''

Comment (PlasmaPower) [inline lib/application.js]: That's the current behavior, changing that would be breaking for no reason. Also, it's better because it keeps the type.

**Comment by RHavar** [comment]
Nice work, if no one objects to it -- it'd be nice to backport this fix to koa 1 as well

**Comment by dougwilson** [comment]
Since removeAddress calls into native code, I wonder what the performance hit this will add to every request, for those bot even getting the IP in their code.

**Comment by PlasmaPower** [comment]
Travis is running benchmarks now, let me check

File: lib/application.js (hunk 1 above)
Comment (RHavar) [inline lib/application.js]: Well I think the nice thing would be to guarantee that every request has an ip. That removes the burden from users of the library to wonder (and check) if it's  ''. I don't really see any reason why a request should be processed that can't get an ip

**Comment by PlasmaPower** [comment]
There doesn't seem to be a noticeable difference on my machine, on Travis it's 10% faster but I'd assume that's not reliable.

File: lib/application.js (hunk 1 above)
Comment (PlasmaPower) [inline lib/application.js]: We can't guarantee that in this section of code though, if `req.socket.remoteAddress` is undefined what do we do? Make up an IP?

**Comment by dougwilson** [comment]
So sounds negligible.

File: lib/application.js (hunk 1 above)
Comment (RHavar) [inline lib/application.js]: Or error out? Perhaps we shouldn't even be continuing.

Comment (PlasmaPower) [inline lib/application.js]: A getter shouldn't error.

Comment (RHavar) [inline lib/application.js]: I don't think an error breaks any behavior, because the request will merely not be created and not processed. From a middlware's perspective, it simply never gets called

**Comment by kraghack** [comment]
Shouldn't the stable major-point release of Koa (v1) be patched as well instead of just the v2 version that's not going to be stable until async/await lands in v8?

File: lib/application.js (hunk 1 above)
Comment (PlasmaPower) [inline lib/application.js]: Oh, sorry I thought this was still a getter for request.ip. I guess throwing an error might work then. Anyone else have an opinion?

**Comment by PlasmaPower** [comment]
@kraghack I'm pretty sure v2 is going to be stable sooner than async/await.

File: lib/application.js (hunk 1 above)
Comment (PlasmaPower) [inline lib/application.js]: Another problem is I'd have to be checking `req && req.headers` anyway because of badly written tests.

Comment (dead-horse) [inline lib/application.js]: we'd better fix those test cases rather than add some check here IMO.

Comment (PlasmaPower) [inline lib/application.js]: Fixing the test cases wouldn't be easy, there are a lot of them and with the above mentioned change we'd have to add both headers and ip. However, I should be able to "fill in" missing attributes.

Also @dead-horse do you think we should throw here if there's no IP? That would essentially mean the request doesn't get processed.

**Comment by PlasmaPower** [comment]
Okay I changed a bunch of things up but it can't be backported to 0.12 easily now.

**Comment by jonathanong** [comment]
looks fine to me. anyone else? @Koajs

File: lib/application.js (hunk 1 above)
Comment (dead-horse) [inline lib/application.js]: I'm not sure if we should throw here(don't know what's the impact when can't get IP), but at lease we should give more detailed information here rather than just an assert.

**Comment by jonathanong** [comment]
@PlasmaPower i think the tests will pass again if you rebase. i upgraded the eslint packages

File: lib/application.js (hunk 1 above)
Comment (PlasmaPower) [inline lib/application.js]: > don't know what's the impact when can't get IP

The request won't be handled. An app error will occur I think.
If we're not throwing, what do you think the default should be @dead-horse? Undefined? An empty string?

**Comment by PlasmaPower** [comment]
Yep, tests seem to be passing now.

File: lib/application.js (hunk 1 above)
Comment (dead-horse) [inline lib/application.js]: after reading https://nodejs.org/api/net.html#net_socket_remoteaddress , I'm -1 on throw here, lose `ip` here mainly cause by client side error(etc: client disconnected), but assert here may record as a server side error(500). 

I'd like default to empty string so the return type of `request.ip` keep the same.

Comment (PlasmaPower) [inline lib/application.js]: Well I guess we could try-catch createContext and if it fails return. A request where the client immediately disconnected shouldn't be processed IMO.

Comment (dead-horse) [inline lib/application.js]: maybe no need to do to many things in the framework level. and in the real world, most of node server is behind a `nginx` server and rarely in this situation.

Comment (PlasmaPower) [inline lib/application.js]: This could remove rate limiting if the attacker doesn't need the result of the request. I'd prefer we don't handle the request. However, the impact is minimal so I'll change it back to `|| ''` unless anybody else has a comment.

**Comment by PlasmaPower** [comment]
It now defaults to '' at the request of @dead-horse.

**Comment by dead-horse** [comment]
LGTM

**Comment by fengmk2** [comment]
+1

**Comment by PlasmaPower** [comment]
I just rebased, tests are still passing, this should be ready to merge.

**Comment by luckydrq** [comment]
+1. Should we also make a PR for koa v1.x then?
